backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:

  - name: "pages"
    label: "Pages"
    description: >
      These are all the standard pages of the website.
    editor:
     preview: false
    files:
      - file: "src/pages/about.md"
        label: "About"
        name: "about"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "standard-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Main Image", name: "image", widget: "image", required: false}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/oddfellows-hall.md"
        label: "Oddfellows Hall"
        name: "oddfellows-hall"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "standard-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Main Image", name: "image", widget: "image", required: false}
          - {label: "Body", name: "body", widget: "markdown"}
          - label: "Oddfellows Gallery"
            name: "oddfellowsGallery"
            widget: "list"
            fields:
              - {label: "Title", name: "title", widget: "string" }
              - {label: "Image", name: "image", widget: "image"}
      - file: "src/pages/gigs.md"
        label: "Gigs"
        name: "gigs"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "standard-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Main Image", name: "image", widget: "image", required: false}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/guestbook.md"
        label: "Guestbook"
        name: "guestbook"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "standard-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Main Image", name: "image", widget: "image", required: false}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/discography.md"
        label: "Discography"
        name: "discography"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "standard-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Main Image", name: "image", widget: "image", required: false}
          - {label: "Body", name: "body", widget: "markdown"}

  - name: "gigs"
    label: "-- Gigs"
    editor:
     preview: false
    description: >
      This lists all the gigs that are displayed on the website. Be aware the date will need to be entered twice - one for sorting chronologically, and one for displaying to end users
    label_singular: 'Gig'
    folder: "src/gigs"
    create: true
    identifier_field: location
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "gig-listing"}
      - {label: "Location", name: "location", widget: "string"}
      - {label: "Date", name: "date", widget: "date", format: "X"}
      - {label: "Date / Time", name: "datetime", widget: "datetime", format: "LLLL"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "discography"
    label: "-- Discography"
    editor:
     preview: false
    description: >
      This lists all the Shantymen albums.
    label_singular: 'Discography'
    folder: "src/discography"
    create: true
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "album-listing"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Artwork", name: "artwork", widget: "image"}
      - {label: "Release Year", name: "release-year", widget: "string"}
      - {label: "Track Listing", name: "body", widget: "markdown"}